### ISSUE TITLE
Infografía fases de la gestión de proyectos

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/infografia-JulioCesar69#2]
![Infografía Software](https://user-images.githubusercontent.com/72415467/132253395-923344f6-00aa-415b-af38-cc49149bbb0a.jpg)

**Comment by antoniio** [comment]
20 %
Un trabajo muy bien elaborado, felicidades.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
